### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by deone** [MeteorAcademy/meteor.academy#1]
I think here's what you meant on these lines;

Hm. Is there such a thing as a basic content _managament_ system?
Hm. Is there such a thing as a basic content _management_ system?

The _bolded_ text are links to the tools you'll need to get through these tutorials.
The _bold_ text are links to the tools you'll need to get through these tutorials.

**Comment by CiaraBurkett** [comment]
Ah, thanks for the corrections!  Sorry the response took so long, I don't think I got a notification when you created the issue.

**Comment by deone** [comment]
That's okay. :)

On Fri, Oct 24, 2014 at 4:42 PM, Ciara Burkett notifications@github.com
wrote:

> Ah, thanks for the corrections! Sorry the response took so long, I don't
> think I got a notification when you created the issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MeteorAcademy/meteor.academy/issues/1#issuecomment-60405561
> .

## 

Oladayo Osikoya. Prosecutors will be violated.
